### ISSUE TITLE
"calibrator_paths" parameter in $genienlp server

### ISSUE THREAD

**Issue by vinith-reddy25** [stanford-oval/decaNLP#248]
I generated a .pkl file using

$genienlp predict --tasks almond --data <datadir> --path <model_dir> --save_confidence_features --confidence_feature_path <confidence_feature_file>

Then I tried to pass that .pkl file as a value of parameter calibrator_path. It is giving following errror:

_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by s-jse** [comment]
Please follow up on this in #247, as these two issues are likely connected.
